
import Head from 'next/head'
import dynamic from 'next/dynamic'

const CustomEditor = dynamic(() => import('../components/Editor'), { ssr: false })
const Editor = dynamic(() => import('../components/EditorTest2'), { ssr: false })
// const CustomEditor = dynamic(() => import('../components/EditorTest'), { ssr: false })

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Editor /> */}
      <CustomEditor />
    </div>
  )
}
